// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZAZAHZYrE7IbCLeNeIK6oaOAyQ8C6xE',
    appId: '1:814209279052:web:8e86f8e0f067e6224f40e9',
    messagingSenderId: '814209279052',
    projectId: 'flutter-application-e4f27',
    authDomain: 'flutter-application-e4f27.firebaseapp.com',
    storageBucket: 'flutter-application-e4f27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPjaX7u8jvMBkrOGealUu7zpuiudBX5S0',
    appId: '1:814209279052:android:ce42a4d7baf070a04f40e9',
    messagingSenderId: '814209279052',
    projectId: 'flutter-application-e4f27',
    storageBucket: 'flutter-application-e4f27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJtMd-HnAAMim3RW3wh-gUp1M_d4KQ_PY',
    appId: '1:814209279052:ios:3edb36cb605d73324f40e9',
    messagingSenderId: '814209279052',
    projectId: 'flutter-application-e4f27',
    storageBucket: 'flutter-application-e4f27.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJtMd-HnAAMim3RW3wh-gUp1M_d4KQ_PY',
    appId: '1:814209279052:ios:b7e5ef346b4744654f40e9',
    messagingSenderId: '814209279052',
    projectId: 'flutter-application-e4f27',
    storageBucket: 'flutter-application-e4f27.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
